### ISSUE TITLE
Use godep to manage dependency

### ISSUE THREAD

**Issue by tobegit3hub** [hyper-carrot/talon#1]
Then we don't have to write it in readme like this.

Dependencies
* github.com/PuerkitoBio/goquery (for parse html-formatted test)
* code.google.com/p/go.net/publicsuffix (for customize http.CookieJar)

**Comment by my-3157** [comment]
当 crawldepth 较大时，会不断产生goroutine ,直到吃尽内存(goroutine 不会销毁)

**Comment by tobegit3hub** [comment]
close this because it doesn't matter :smiley:
